### ISSUE TITLE
v1.1.1 is not published

### ISSUE THREAD

**Issue by MathieuDerelle** [Beetrack/fish_transactions#1]
Is it normal that v1.1.1 is not published ?
https://rubygems.org/gems/fish_transactions/versions/1.1

what's the difference between "1.1.1" and "v1.1.1" ?

**Comment by MathieuDerelle** [comment]
there's also a typo 

https://github.com/Beetrack/fish_transactions/blob/d95dd97b744ffe00888f69cdb3d0377106bc0320/lib/fish_transactions/callbacks.rb#L134
`does not run`

**Comment by kalelc** [comment]
Hello, @MathieuDerelle Excuse us, but this project is deprecated. Maybe I could help you; What do you need to do?

**Comment by MathieuDerelle** [comment]
Since https://github.com/rails/rails/issues/26045 will never be solved, I'm using this gem to schedule jobs after transactions in rails 5

It does not feel good to target a specific repo/branch

**Comment by kalelc** [comment]
your transactions are in workers? you could use Sidekiq Batches and use a trigger to callback schedule jobs.
